### ISSUE TITLE
hello, i want your help

### ISSUE THREAD

**Issue by star19990** [gdkchan/MESTool#3]
hello i want pc version bayonetta translate,
but i dont konw where .mes file and Subtitle file(Is there an .mes file in the cpk file?)
how to find that?
and what is  
Error: "Texts.txt" not found on folder 123!
Warning: "TextureMap.xml" not found on folder 123!
??

**Comment by DropsMJay** [comment]
The files are inside data13.cpk

**Comment by star19990** [comment]
Thank you, but I still have one more problem.
I entered "mestool -d -pc -all"
However, "unhandled Exception : OutOfMemoryException." This is output.
how to fix this?
(i use subscr000.mes file)

**Comment by gdkchan** [comment]
-all will try to extract all files. To extract just the file you mentioned you should use "mestool -d -pc subscr000.mes".

**Comment by star19990** [comment]
i enter "mestool -d -pc subscr000.mes"
But the still same problem

**Comment by gdkchan** [comment]
I can't reproduce your issue. I tried extracting this file with the tool and it is extracted successfully. I also re-created it and extracted again, and it was extracted without problems.

**Comment by star19990** [comment]
hum... maybe my visual studio 2015 something wrong
What version of visual studio do you use?
and windows
i use win10 64 bit

**Comment by gdkchan** [comment]
Visual Studio 2015 Community running on Win10 aswell.

**Comment by star19990** [comment]
I found a reason.
Because  my visual studio 2015 Build settings is 32-bit was the default
Thank you very much for your help.
